export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const PENDING_CHARACTERS = 'PENDING_CHARACTERS';
export const CHARACTERS_REJECT = 'CHARACTERS_REJECT';
export const FETCH_SINGLECHARACTER = 'FETCH_SINGLECHARACTER';
export const PENDING_SINGLECHARACTER = 'PENDING_SINGLECHARACTER';
export const SINGLECHARACTER_REJECT = 'SINGLECHARACTER_REJECT';
export const CHANGE_PARAMS = 'CHANGE_PARAMS';