export const CHARACTERS = 'CHARACTERS' ;
export const EPISODES = 'EPISODES';
export const LOCATIONS = 'LOCATIONS';
export const SETTINGS = 'SETTINGS';
export const TABNAVIGATOR = 'TABNAVIGATOR';
export const FILTERCHARACTERS = 'FILTERCHARACTERS';
export const CHARACTERDETAIL = 'CHARACTERDETAIL';
export const SEARCHCHARACTERS = 'SEARCHCHARACTERS';